;kakarotto normal by FRS GAMES

                              ;Inteligencia Artificial
[Command]
name = "IA1"
command = a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA2"
command = ~D, DF, F, b,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA3"
command = ~D, DF, F, c,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA4"
command = ~D, DF, F, x,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA5"
command = ~D, DF, F, y,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA6"
command = ~D, DF, F, z,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA7"
command = ~D, DB, B, a,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA8"
command = ~D, DB, B, b,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA9"
command = ~D, DB, B, c,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA10"
command = ~D, DB, B, x,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA11"
command = ~D, DB, B, y,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name ="IA12"
command = ~D, DB, B, z,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA13"
command = ~D, DB, B, c,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA14"
command = ~D, DB, B, x,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name = "IA15"
command = ~D, DB, B, y,a+b+c+z+x+y+U+D+F+B
time = 1

[Command]
name ="IA16"
command = ~D, DB, B, z,a+b+c+z+x+y+U+D+F+B
time = 1
[Command]
name = "kaioken"
command = z
time = 1
[Command]
name = "ssj2"
command = a+b
time = 1
[Command]
name = "ssj2maximo"
command = z
time = 1
[Command]
name = "meteor ss2 max"
command = D, DB, B, F, c
time = 30
[Command]
name = "3chutes subindo"
command = ~D, DF, F, a
time = 7
[Command]
name = "goku tornado"
command = D, DB, B, F, a
time = 30
[Command]
name = "espancamento kaioken"
command = D, DB, B, F, c
time = 30
[Command]
name = "wkame"
command = D, DB, B, F, x
time = 30
[Command]
name = "ssj2 combo"
command = D, DF, F, x
time = 10
[Command]
name = "ssj2 combo2"
command = D, DF, F, y
time = 10
[Command]
name = "mkame"
command = D, DB, B, F, y
time = 30
[Command]
name = "shkame"
command = D, DB, B, F, z
time = 30
[Command]
name = "genkidama"
command = D, DB, B, F, c
time = 30
[Command]
name = "ssj2 genkidama"
command = D, DB, B, F, c
time = 30
[Command]
name = "renzoku"
command = D, DB, B, F, b
time = 30
[Command]
name = "meteor1"
command = D, DB, B, F, a
time = 30
[Command]
name = "Bukuu Jutsu"
command = b+y
[Command]
name = "fireball"
command =  c
time = 1
[Command]
name = "goku sequencia"
command = ~D, DF, F, y
time = 10
[Command]
name = "goku sequencia2"
command = ~D, DF, F, x
time = 10
[Command]
name = "fazer sequencia aerea2"
command = ~D, DF, F, a
time = 10
[Command]
name = "fazer sequencia aerea ssj2"
command = ~F, D, DF, a
[Command]
name = "fazer sequencia aerea ssj2"
command = ~F, D, DF, b
[Command]
name = "fireball x3"
command = ~D, DF, F, c
time = 7
[Command]
name = "taioken"
command = ~D, DB, B, x
time = 7
[Command]
name = "teleport"
command = a+x
[Command]
name = "ufire"
command = /UF
time = 1
[Command]
name = "dfire"
command = /DF
time = 1

[Command]
name = "bufire"
command = /UB
time = 1
[Command]
name = "bdfire"
command = /DB
time = 1
[Command]
name = "airattack"
command = ~D, DF, F, b
[Command]
name = "airattack"
command = ~D, DF, F, a
[Command]
name = "dbattack"
command = ~D, DB, B, a
[Command]
name = "cicle kick"
command = ~D, DB, B, b
time = 7
[Command]
name = "rollfwd"
command = ~D, DF, F, b
time = 7
[Command]
name = "invisible"
command =  ~D, DB, B, y
time = 7
[Command]
name = "quick"
command = ~D, DB, B, c
[Command]
name = "QCF_a"
command = ~D, DF, F, a
[Command]
name = "QCF_b"
command = ~D, DF, F, b
[Command]
name = "QCF_c"
command = ~D, DF, F, c
[Command]
name = "QCF_x"
command = ~D, DF, F, x
[Command]
name = "QCF_y"
command = ~D, DF, F, y
[Command]
name = "QCF_z"
command = ~D, DF, F, z
[Command]
name = "QCB_a"
command = ~D, DB, B, a
[Command]
name = "QCB_b"
command = ~D, DB, B, b
[Command]
name = "QCB_c"
command = ~D, DB, B, c
[Command]
name = "QCB_x"
command = ~D, DB, B, x
[Command]
name = "QCB_y"
command = ~D, DB, B, y
[Command]
name = "QCB_z"
command = ~D, DB, B, z
[Command]
name = "uppercut_a"
command = ~F, D, DF, a
[Command]
name = "uppercut_b"
command = ~F, D, DF, b
[Command]
name = "uppercut_c"
command = ~F, D, DF, c
[Command]
name = "uppercut_x"
command = ~F, D, DF, x
[Command]
name = "uppercut_y"
command = ~F, D, DF, y
[Command]
name = "uppercut_z"
command = ~F, D, DF, z
[Command]
name = "chargedownup_a"
command = ~60$D, U, a
time = 10
[Command]
name = "chargedownup_b"
command = ~60$D, U, b
time = 10
[Command]
name = "chargedownup_c"
command = ~60$D, U, c
time = 10
[Command]
name = "chargedownup_x"
command = ~60$D, U, x
time = 10
[Command]
name = "chargedownup_y"
command = ~60$D, U, y
time = 10
[Command]
name = "chargedownup_z"
command = ~60$D, U, z
time = 10
[Command]
name = "chargebackfwd_a"
command = ~60$B, F, a
time = 10
[Command]
name = "chargebackfwd_b"
command = ~60$B, F, b
time = 10
[Command]
name = "chargedownup_c"
command = ~60$D, U, c
time = 10
[Command]
name = "chargedownup_x"
command = ~60$D, U, x
time = 10
[Command]
name = "chargedownup_y"
command = ~60$D, U, y
time = 10
[Command]
name = "chargedownup_z"
command = ~60$D, U, z
time = 10
[Command]
name = "FF"
command = F, F
time = 10
[Command]
name = "BB"
command = B, B
time = 10
[Command]
name = "recovery"
command = a+b
time = 1
[Command]
name = "ab"
command = a+b
time = 1
[Command]
name = "fwd_a"
command = /F,a
time = 1
[Command]
name = "fwd_b"
command = /F,b
time = 1
[Command]
name = "fwd_c"
command = /F,c
time = 1
[Command]
name = "fwd_x"
command = /F,x
time = 1
[Command]
name = "fwd_y"
command = /F,y
time = 1
[Command]
name = "fwd_z"
command = /F,z
time = 1
[Command]
name = "back_a"
command = /B,a
time = 1
[Command]
name = "back_b"
command = /B,b
time = 1
[Command]
name = "back_c"
command = /B,c
time = 1
[Command]
name = "down_a"
command = /$D,a
time = 1
[Command]
name = "down_b"
command = /$D,b
time = 1
[Command]
name = "down_c"
command = /$D,c
time = 1
[Command]
name = "fwd_ab"
command = /F, a+b
time = 1
[Command]
name = "back_ab"
command = /B, a+b
time = 1
[Command]
name = "a"
command = a
time = 1
[Command]
name = "b"
command = b
time = 1
[Command]
name = "c"
command = c
time = 1
[Command]
name = "x"
command = x
time = 1
[Command]
name = "y"
command = y
time = 1
[Command]
name = "z"
command = z
time = 1
[Command]
name = "start"
command = s
time = 1
[Command]
name = "holdfwd"
command = /$F
time = 1
[Command]
name = "holdback";
command = /$B
time = 1
[Command]
name = "holdup"
command = /$U
time = 1
[Command]
name = "holddown"
command = /$D
time = 1
[Command]
name = "UU"
command = U, U
time = 15
[Command]
name = "DD"
command = D, D
time = 15
[Command]
name = "holdx"
command = /x
time = 1
[Command]
name = "holdy"
command = /y
time = 1
[Command]
name = "holdz"
command = /z
time = 1
[Command]
name = "holda"
command = /a
time = 1
[Command]
name = "holdb"
command = /b
time = 1
[Command]
name = "holdc"
command = /c
time = 1
[Statedef -1]
[State -1]
type = ChangeState
trigger1 = IsHelper(56)
value = 56
[State -1]
type = varset
triggerall = var(6) != 1
trigger1 = command = "IA1"
trigger2 = command = "IA2"
trigger3 = command = "IA3"
trigger4 = command = "IA4"
trigger5 = command = "IA5"
trigger6 = command = "IA6"
trigger7 = command = "IA7"
trigger8 = command = "IA8"
trigger9 = command = "IA9"
trigger10 = command = "IA10"
trigger11 = command = "IA11"
trigger12 = command = "IA12"
trigger13 = command = "IA13"
trigger14 = command = "IA14"
trigger15 = command = "IA15"
trigger16 = command = "IA16"
v = 6
value = 1
[State -1]
type = ChangeState
value = 1002999
triggerall = var(1) = 2 || var(1) = 3
triggerall  = command = "3chutes subindo"
trigger1 = (statetype = S) && (ctrl)
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1]
type = ChangeState
value = 87479891
triggerall = var(1) = 2 || var(1) = 3
triggerall = command = "ssj2 combo2"
trigger1 = statetype != A
trigger1 = ctrl
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1]
type = ChangeState
value = 20409
triggerall = command = "ssj2 combo"
triggerall = var(1) = 2 ||  var(1) = 3
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = changestate
value = 8080
triggerall = command = "meteor ss2 max"
triggerall = numproj = 0
triggerall = power = 3000
triggerall = var(1) = 3
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1]
type = changestate
value = 2020989
triggerall = var(1) = 2
triggerall = command = "ssj2 genkidama"
triggerall = numproj = 0
triggerall = power >= 3000
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = ChangeState
value = 2800
triggerall = Command = "goku tornado"
triggerall = Power >= 1000
triggerall = var(1) = 2|| var(1) = 3
trigger1 = StateType != A
trigger1 = Ctrl
trigger2 = MoveContact
trigger3 = StateNo = 2500
trigger4 = StateNo = 2410
trigger5 = StateNo = [2402,2405]
trigger6 = StateNo = 2001 && (AnimElemTime(4) >= 1 && AnimElemTime(5) < 0)
[State -1]
type = changestate
triggerall = var(1) = 2 || var(1) = 3
value = 800099
triggerall = command = "shkame"
triggerall = numproj = 0
triggerall = power > 2500
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1 ]
type = ChangeState
triggerall = var(1) = 1
value = 28009
triggerall = command = "espancamento kaioken"
trigger1 = power >2500
trigger1 = statetype != A
trigger1 = ctrl
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1]
type = ChangeState
value = 100299
triggerall = var(1) = 0 || var(1) = 1
triggerall  = command = "fazer sequencia aerea2"
trigger1 = (statetype = S) && (ctrl)
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1]
type = ChangeState
value = 100299
triggerall = var(1) = 2 || var(1) = 3
triggerall  = command = "fazer sequencia aerea ssj2"
trigger1 = (statetype = S) && (ctrl)
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1, Taunt]
type = ChangeState
value = 195
triggerall = command = "start"
triggerall = var(1) = 0 || var(1) = 1
trigger1 = statetype != A
trigger1 = ctrl
[State -1, Taunt]
type = ChangeState
value = 9195
triggerall = command = "start"
triggerall = var(1) = 2 || var(1) = 3
trigger1 = statetype != A
trigger1 = ctrl
[State -1]
type = ChangeState
value = 275989
triggerall = var(1) = 0 || var(1) = 1
triggerall = command = "goku sequencia"
trigger1 = statetype != A
trigger1 = ctrl
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1]
type = ChangeState
value = 8747
triggerall = var(1) = 0 || var(1) = 1
triggerall = command = "goku sequencia2"
trigger1 = statetype != A
trigger1 = ctrl
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1]
type = ChangeState
value = 730
triggerall = command = "holda"
triggerall = command = "holdb"
triggerall = power < 3000
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 1510
[State -1]
type = ChangeState
value = 2300
triggerall = command = "quick"
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
[State -1]
type = ChangeState
value = 2205
triggerall = command = "invisible"
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = ChangeState
value = 2200
triggerall = command = "rollfwd"
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = changestate
value = 8070
triggerall = power > 2500
triggerall = command = "meteor1"
triggerall = numproj = 0
triggerall = power > 0
triggerall = var(1) = 1
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1]
type = changestate
value = 8060
triggerall = command = "meteor1"
triggerall = numproj = 0
triggerall = power = 3000
triggerall = var(1) = 0
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger2  = (movecontact)
[State -1]
type = changestate
value = 8020
triggerall = command = "renzoku"
triggerall = numproj = 0
triggerall = power > 1500
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = changestate
triggerall = var(1) = 0 || var(1) = 1
value = 8000
triggerall = command = "shkame"
triggerall = numproj = 0
triggerall = power > 0
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = ChangeState
value = 2040
triggerall = command = "cicle kick"
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = changestate
value = 2020
triggerall = var(1) = 0
triggerall = command = "genkidama"
triggerall = numproj = 0
triggerall = power >= 2500
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = ChangeState
value = 2010
triggerall = command = "dbattack"
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = ChangeState
value = 2000
triggerall = command = "teleport"
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = ChangeState
value = 1980
trigger1 = command = "airattack"
trigger1 = statetype = A
trigger1 = ctrl = 1
[State -1]
type = changestate
value = 2030
triggerall = command = "mkame"
triggerall = numproj = 0
triggerall = power > 0
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = changestate
value = 1900
triggerall = command = "wkame"
triggerall = numproj = 0
triggerall = power > 0
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = changestate
value = 1800
triggerall = command = "taioken"
triggerall = numproj = 0
triggerall = power >= 500
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = changestate
value = 1050
triggerall = command = "fireball x3"
triggerall = numproj = 0
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
trigger3  = (stateno = 200) || (stateno = 205)|| (stateno = 210)|| (stateno = 215)
trigger3  = (movecontact)
[State -1]
type = changestate
value = 1000
triggerall = command = "c"
triggerall = numproj = 0
trigger1 = statetype != C
trigger1 = ctrl = 1
trigger2 = stateno = 1510
[State -1]
type = changestate
value = 2999
triggerall = var(1) = 0
triggerall = power = 3000
trigger1 = command = "ssj2"
trigger1 = statetype = S
[State -1]
type = changestate
value = 736
triggerall = var(1) = 2
triggerall = power = 3000
triggerall = command = "ssj2maximo"
trigger1 = statetype = S
[State -1]
type = changestate
value = 500
triggerall = var(1) = 0
triggerall = power >= 1500
trigger1 = command = "kaioken"
trigger1 = statetype = S
[State -1]
type = ChangeState
value = 1500
triggerall = command = "Bukuu Jutsu"
trigger1 = statetype = S
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 1510
triggerall = command = "Bukuu Jutsu"
trigger1 = statetype = A
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 100
trigger1 = command = "FF"
trigger1 = statetype = S
trigger1 = ctrl = 1
[State -1]
type = ChangeState
value = 105
trigger1 = command = "BB"
trigger1 = statetype = S
trigger1 = ctrl = 1
[State -1]
type = null; ChangeState
value = 900
triggerall = statetype = S
triggerall = ctrl = 1
triggerall = p2bodydist X < 5 ;Near P2
trigger1 = command = "fwd_b";p2 stand
trigger1 = stateno != 100    ;Not running
trigger1 = p2statetype = S
trigger1 = p2movetype != H
trigger2 = command = "fwd_b";p2 crouch
trigger2 = stateno != 100    ;Not running
trigger2 = p2statetype = C
trigger2 = p2movetype != H
trigger3 = command = "back_b";p2 stand
trigger3 = p2statetype = S
trigger3 = p2movetype != H
trigger4 = command = "back_b";p2 crouch
trigger4 = p2statetype = C
trigger4 = p2movetype != H
[State -1]
type = null; ChangeState
value = 950
triggerall = statetype = A
triggerall = ctrl = 1
triggerall = p2bodydist X < 9
triggerall = p2bodydist Y > -22
triggerall = p2bodydist Y < 22
triggerall = p2statetype = A
triggerall = p2movetype != H
trigger1 = command = "fwd_b"
trigger2 = command = "back_b"
[State -1]
type = ChangeState
value = 200
triggerall = command = "x";Place name of command here
triggerall = command != "holddown";Standing moves should have this line
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 200
trigger3 = stateno = 210
trigger3 = MoveContact  
trigger4 = stateno = 215
trigger4 = MoveContact  
trigger5 = stateno = 205
trigger5 = MoveContact
trigger6 = stateno = 1510
[State -1]
type = ChangeState
value = 205
triggerall = command = "y"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 210
trigger2 = MoveContact  
trigger3 = stateno = 215
trigger3 = MoveContact  
trigger4 = stateno = 200
trigger4 = MoveContact   
trigger5 = stateno = 1510
[State -1]
type = ChangeState
value = 210
triggerall = command = "b"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 200
trigger2 = MoveContact  ;If move hits, or is guarded by opponent
trigger3 = stateno = 215
trigger3 = MoveContact  
trigger4 = stateno = 205
trigger4 = MoveContact   
trigger5 = stateno = 1510
[State -1]
type = ChangeState
value = 215
triggerall = command = "a"
triggerall = command != "holddown"
trigger1 = statetype = S
trigger1 = ctrl = 1
trigger2 = stateno = 200
trigger2 = MoveContact  ;If move hits, or is guarded by opponent
trigger3 = stateno = 210
trigger3 = MoveContact  
trigger4 = stateno = 205
trigger4 = MoveContact
trigger5 = stateno = 1510
[State -1]
type = ChangeState
value = 400
triggerall = command = "x"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
trigger2 = stateno = 210
trigger2 = MoveContact  
trigger3 = stateno = 215
trigger3 = MoveContact  
trigger4 = stateno = 200
trigger4 = MoveContact
trigger5 = stateno = 205
trigger5 = MoveContact  
trigger6 = stateno = 410
trigger6 = MoveContact  
[State -1]
type = ChangeState
value = 410
triggerall = command = "a"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
trigger2 = stateno = 210
trigger2 = MoveContact
trigger3 = stateno = 215
trigger3 = MoveContact
trigger4 = stateno = 200
trigger4 = MoveContact
trigger5 = stateno = 205
trigger5 = MoveContact
trigger6 = stateno = 400
trigger6 = MoveContact
[State -1]
type = ChangeState
value = 401
triggerall = command = "y"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
trigger2 = stateno = 210
trigger2 = MoveContact  
trigger3 = stateno = 215
trigger3 = MoveContact  
trigger4 = stateno = 200
trigger4 = MoveContact
trigger5 = stateno = 205
trigger5 = MoveContact  
trigger6 = stateno = 410
trigger6 = MoveContact  
[State -1]
type = ChangeState
value = 411
triggerall = command = "b"
triggerall = command = "holddown"
trigger1 = statetype = C
trigger1 = ctrl = 1
trigger2 = stateno = 210
trigger2 = MoveContact  
trigger3 = stateno = 215
trigger3 = MoveContact  
trigger4 = stateno = 200
trigger4 = MoveContact
trigger5 = stateno = 205
trigger5 = MoveContact  
trigger6 = stateno = 400
trigger6 = MoveContact
[State -1]
type = ChangeState
value = 600
trigger1 = command = "y"
trigger1 = statetype = A
trigger1 = ctrl = 1
trigger2 = stateno = 601
trigger2 = MoveContact
[State -1]
type = ChangeState
value = 601
trigger1 = command = "x"
trigger1 = statetype = A
trigger1 = ctrl = 1
trigger2 = stateno = 610
trigger2 = MoveContact
[State -1]
type = ChangeState
value = 610
trigger1 = command = "a"
trigger1 = statetype = A
trigger1 = ctrl = 1
trigger2 = stateno = 601
trigger2 = MoveContact
[State -1]
type = ChangeState
value = 611
trigger1 = command = "b"
trigger1 = statetype = A
trigger1 = ctrl = 1
trigger2 = stateno = 600
trigger2 = MoveContact

